# Generated by Django 5.1.5 on 2025-02-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('orderdate', models.DateTimeField()),
            ],
        ),
    ]
